# Lexer for Emmy

lex = {
    '1a' : 'rol',
    'f6' : 'ror',
    'ff' : 'ils',
    'a9' : 'ile',
    'ed' : 'icr',
    '0e' : 'dcr',
    '6a' : 'wls',
    'c5' : 'wle',
    'be' : 'acc',
    '8e' : 'dcc',
    '98' : 'ast',
    '1b' : 'cst',
    '5d' : 'inp',
    '04' : 'out',
    '13' : 'xor',
    'e3' : 'pls',
    '2a' : 'mns',
    '11' : 'num',
    'c7' : 'rnd',
    'c4' : 'xpl',
    'ee' : 'emy',
    '12' : 'bob',
    '14' : 'hwd',
    'bb' : 'gds',
    'f5' : 'nin',
    }
